when:
  instance: ci.kokuwa.io
  repo: woodpecker/backstage-entity-validator
  event: [manual, push]
  branch: main
  path: [.woodpecker/dockerhub.yaml, README.md]

steps:

  metadata:
    image: kokuwaio/dockerhub-metadata
    settings:
      repository: kokuwaio/backstage-entity-validator
      description-short: A WoodpeckerCI plugin for backstage-entity-validator to lint backstage entities.
      categories: [developer-tools, integration-and-delivery]
      username: {from_secret: dockerhub_username}
      password: {from_secret: dockerhub_password}
